### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

array = np.random.randint(1, 50, size=10)
media = np.mean(array)
desvio_padrao = np.std(array)

print("Array:\n", array)
print("\n Media:\n", media)
print("\n Desvio padrão:\n", desvio_padrao)

Array:
 [48 33 48 15 13 48 26  2  7 45]

 Media:
 28.5

 Desvio padrão:
 17.396838793298052


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
array = np.random.rand(10)

#Calcula a raiz quadrada de numeros menores que 0.5:
array[array <= 0.5] = np.sqrt(array[array <= 0.5])

print(array)

[0.52417888 0.74284396 0.55450844 0.56567491 0.66179019 0.54346082
 0.77221975 0.4579011  0.53849665 0.6188905 ]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3, 3, 3)

maiores_valores = np.amax(matriz, axis=1)

print("Matriz original:\n", matriz)
print("\n Maiores valores de cada linha:\n", maiores_valores)

Matriz original:
 [[[0.62485331 0.03387338 0.90873593]
  [0.96709048 0.49397602 0.07669219]
  [0.25777865 0.47344956 0.84761621]]

 [[0.4873354  0.23552674 0.08298839]
  [0.9704478  0.49879503 0.05863512]
  [0.16429824 0.05433603 0.78668445]]

 [[0.73835635 0.89734524 0.55951789]
  [0.28781354 0.72867949 0.4046231 ]
  [0.94769189 0.56899382 0.54218909]]]

 Maiores valores de cada linha:
 [[0.96709048 0.49397602 0.90873593]
 [0.9704478  0.49879503 0.78668445]
 [0.94769189 0.89734524 0.55951789]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
array = np.random.rand(5, 5)

array_sub = np.mean(array, axis=1)

media_linha = array - array_sub[:, np.newaxis]

print("Array original:\n", array)
print("\n Média das linhas:\n", array_sub)
print("\n Subtração pela media:\n", media_linha)

Array original:
 [[0.51408967 0.62748993 0.51110777 0.34025732 0.85972315]
 [0.89932631 0.69567334 0.12256282 0.30583216 0.75194764]
 [0.5182385  0.9481493  0.82530551 0.02779324 0.60348965]
 [0.97201271 0.01225154 0.46630452 0.23295925 0.31678294]
 [0.03077121 0.39527283 0.42650785 0.83864357 0.86792766]]

 Média das linhas:
 [0.57053357 0.55506845 0.58459524 0.40006219 0.51182462]

 Subtração pela media:
 [[-0.0564439   0.05695636 -0.0594258  -0.23027625  0.28918958]
 [ 0.34425785  0.14060489 -0.43250563 -0.2492363   0.19687919]
 [-0.06635674  0.36355406  0.24071027 -0.556802    0.01889441]
 [ 0.57195052 -0.38781065  0.06624233 -0.16710295 -0.08327925]
 [-0.48105341 -0.1165518  -0.08531677  0.32681894  0.35610304]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4, 4)

# Calcular a média e o desvio padrão das diagonais da matriz
diag_principal = np.diag(matriz)
diag_secundaria = np.diag(np.fliplr(matriz))
media_diag = np.mean([diag_principal, diag_secundaria])
std_diag = np.std([diag_principal, diag_secundaria])

print("Matriz:\n", matriz)
print("\n Diagonal principal:\n", diag_principal)
print("\n Diagonal secundária:\n", diag_secundaria)
print("\n Média das diagonais:", media_diag)
print("\n Desvio padrão das diagonais:", std_diag)

Matriz:
 [[0.82677433 0.91301131 0.42188512 0.05916133]
 [0.43389663 0.27890085 0.45985123 0.26063068]
 [0.54313583 0.30209731 0.10713688 0.94262397]
 [0.36486248 0.62331409 0.78037473 0.88075819]]

 Diagonal principal:
 [0.82677433 0.27890085 0.10713688 0.88075819]

 Diagonal secundária:
 [0.05916133 0.45985123 0.30209731 0.36486248]

 Média das diagonais: 0.4099428253412657

 Desvio padrão das diagonais: 0.28361074743727493
